// Port of ink's Error.cs (inkjs Error.ts).

/// Receives errors and warnings as data instead of an exception.
///
/// Assign one to `Story.onError`; without one, the first problem in a
/// continue throws a `StoryException`.
typedef ErrorHandler = void Function(String message, ErrorType type);

/// The kind of problem reported to an [ErrorHandler].
enum ErrorType {
  /// Generated by a "TODO" note in the ink source.
  author,

  /// A problem worth fixing that doesn't stop the story.
  warning,

  /// A problem that stops the current flow.
  error,
}
